const CLUB_LIST_DATA = [
  // {
  //   clubId: 1,
  //   clubName: 'Doit',
  //   clubEnglishName: 'doit',
  //   clubImage: '/logo.svg',
  //   clubDescription:
  //     "아주대학교 프로그래밍 동아리 DoiT!의 이름은 Dream of interworking Team!의 약자입니다. 여기서 'interworking'이라는 단어는 '정보 연결이 가능하다', '두 시스템이 대화하기 위하여 필요한 프로세스' 등의 뜻을 가지고 있습니다.",
  //   clubRoom: '구학생회관 234호',
  //   clubGeneration: '23기',
  //   clubDues: 20000,
  // },
  // {
  //   clubId: 2,
  //   clubName: 'SWeat',
  //   clubEnglishName: 'sweat',
  //   clubImage: '/logo.svg',
  //   clubDescription: '코딩 봉사 교육 동아리 SWeat입니다.',
  //   clubRoom: '학생회관 232호',
  //   clubGeneration: '23기',
  //   clubDues: 15000,
  // },
  // {
  //   clubId: 3,
  //   clubName: '농구부',
  //   clubEnglishName: 'nongu',
  //   clubImage: '/logo.svg',
  //   clubDescription: '농구부원 상시모집',
  //   clubRoom: '학생회관 222호',
  //   clubGeneration: '23기',
  //   clubDues: 25000,
  // },
  // {
  //   clubId: 4,
  //   clubName: '음악동아리',
  //   clubEnglishName: 'music',
  //   clubImage: '/logo.svg',
  //   clubDescription: '음악부원 상시모집',
  //   clubRoom: '학생회관 888호',
  //   clubGeneration: '23기',
  //   clubDues: 10000,
  // },
  // {
  //   clubId: 5,
  //   clubName: '댄스동아리',
  //   clubEnglishName: 'dance',
  //   clubImage: '/logo.svg',
  //   clubDescription: '댄스부원 상시모집',
  //   clubRoom: '학생회관 333호',
  //   clubGeneration: '23기',
  //   clubDues: 15000,
  // },
  {
    clubId: 2,
    clubName: '캡디',
    clubEnglishName: 'capdiy',
    clubImage: '/logo.svg',
    clubDescription: '캡디입니다.',
    clubRoom: '팔달관 309호',
    clubGeneration: '23기',
    clubDues: 10000,
  },
];

export { CLUB_LIST_DATA };
