import { ClubItemCategory, ClubItemResponseData, ClubItemsMyResponseData } from 'types/item';

const CLUB_ITEM_CATEGORY = {
  DIGITAL: '디지털',
  SPORT: '스포츠',
  BOOK: '도서',
  CLOTHES: '의류',
  STATIONERY: '문구류',
  ETC: '기타',
};

const CLIB_ITEM_CATEGORY_MENU: { category: ClubItemCategory; label: string }[] = Object.entries(CLUB_ITEM_CATEGORY).map(
  ([category, label]) => ({ category: category as ClubItemCategory, label }),
);

const CLUB_ITEM_DATA: ClubItemResponseData[] = [
  {
    itemId: 0,
    itemName: '27인치 모니터',
    itemPhoto: '/logo.svg',
    itemDescription: '하둡 프로그래밍에 대해서 알려주는 책이다. 하둡 프로그래밍이 뭔지 알 수 있다.',
    itemLocation: '동아리 방',
    itemCategory: 'DIGITAL',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: false,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 0,
  },
  {
    itemId: 1,
    itemName: '농구공',
    itemPhoto: '/logo.svg',
    itemDescription: '따끈따끈한 농구공이다.',
    itemLocation: '동아리 방',
    itemCategory: 'SPORT',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: true,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 4,
  },
  {
    itemId: 2,
    itemName: '스테이플러',
    itemPhoto: '/logo.svg',
    itemDescription: '따끈따끈한 농구공이다.',
    itemLocation: '동아리 방',
    itemCategory: 'ETC',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: false,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 1,
  },
  {
    itemId: 3,
    itemName: '하둡의 프로그래밍',
    itemPhoto: '/logo.svg',
    itemDescription: '하둡 프로그래밍에 대해서 알려주는 책이다. 하둡 프로그래밍이 뭔지 알 수 있다.',
    itemLocation: '동아리 방',
    itemCategory: 'BOOK',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: false,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 3,
  },
  {
    itemId: 4,
    itemName: '아이폰 충전기',
    itemPhoto: '/logo.svg',
    itemDescription: '하둡 프로그래밍에 대해서 알려주는 책이다. 하둡 프로그래밍이 뭔지 알 수 있다.',
    itemLocation: '동아리 방',
    itemCategory: 'DIGITAL',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: true,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 14,
  },
  {
    itemId: 5,
    itemName: '스피커',
    itemPhoto: '/logo.svg',
    itemDescription: '하둡 프로그래밍에 대해서 알려주는 책이다. 하둡 프로그래밍이 뭔지 알 수 있다.',
    itemLocation: '동아리 방',
    itemCategory: 'DIGITAL',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: false,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 2,
  },
  {
    itemId: 6,
    itemName: '삼겹살',
    itemPhoto: 'https://woohakdong.image.s3.ap-northeast-2.amazonaws.com/temp79826d12-4adf-40bb-bd16-3133da484dd8',
    itemDescription: '삼겹살이라고 했지맘 오겹살이다',
    itemLocation: '경주',
    itemCategory: 'ETC',
    itemRentalMaxDay: 2,
    itemAvailable: true,
    itemUsing: true,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 1,
  },
];

const CLUB_ITEM_MY_DATA: ClubItemsMyResponseData[] = [
  {
    itemId: 1,
    itemName: '농구공',
    itemPhoto: '/logo.svg',
    itemDescription: '따끈따끈한 농구공이다.',
    itemLocation: '동아리 방',
    itemCategory: 'SPORT',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: true,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 4,
    itemBorrowedReturnDate: null,
  },
  {
    itemId: 2,
    itemName: '스테이플러',
    itemPhoto: '/logo.svg',
    itemDescription: '따끈따끈한 농구공이다.',
    itemLocation: '동아리 방',
    itemCategory: 'ETC',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: false,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 1,
    itemBorrowedReturnDate: '2024-11-13T01:00:49.889Z',
  },
  {
    itemId: 5,
    itemName: '스피커',
    itemPhoto: '/logo.svg',
    itemDescription: '하둡 프로그래밍에 대해서 알려주는 책이다. 하둡 프로그래밍이 뭔지 알 수 있다.',
    itemLocation: '동아리 방',
    itemCategory: 'DIGITAL',
    itemRentalMaxDay: 0,
    itemAvailable: true,
    itemUsing: true,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 2,
    itemBorrowedReturnDate: null,
  },
  {
    itemId: 6,
    itemName: '삼겹살',
    itemPhoto: 'https://woohakdong.image.s3.ap-northeast-2.amazonaws.com/temp79826d12-4adf-40bb-bd16-3133da484dd8',
    itemDescription: '삼겹살이라고 했지맘 오겹살이다',
    itemLocation: '경주',
    itemCategory: 'ETC',
    itemRentalMaxDay: 2,
    itemAvailable: true,
    itemUsing: true,
    itemRentalDate: '2024-10-29T05:56:14.799Z',
    itemRentalTime: 1,
    itemBorrowedReturnDate: null,
  },
];

const CLUB_ITEM_SORT_OPTIONS = [
  { label: '전체', id: 0 },
  { label: '비대여 중', id: 1 },
  { label: '대여 중', id: 2 },
  { label: '대여 불가', id: 3 },
];

export { CLUB_ITEM_CATEGORY, CLIB_ITEM_CATEGORY_MENU, CLUB_ITEM_DATA, CLUB_ITEM_MY_DATA, CLUB_ITEM_SORT_OPTIONS };
