const ROUTE = {
  ROOT: '/',
  LOGIN_REGISTER: '/login',
  MEMBER_REGISTER: '/member',
  CLUB_REGISTER: '/club',
  MEMBER_INFO_WRITE: '/member/info/write',
  MEMBER_INFO_CONFIRM: '/member/info/confirm',
  CLUB_LIST: '/club/list',
  CLUB_JOIN_NOTICE: '/club/join/notice',
  CLUB: '/clubs',
  PAYMENT: '/payment',
  PAYMENT_REDIRECT: '/payment/redirect',
  ITEM: '/items',
  ITEM_SEARCH: '/items/search',
  ITEM_MY: '/items/my',
  DUES: '/dues',
  DUES_SEARCH: '/dues/search',
  MEMBER: '/members',
  SCHEDULE: '/schedules',
  ADMIN: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_STATS: '/admin/stats',
  ADMIN_STATS_SCHOOL: '/admin/stats/schools',
  ADMIN_STATS_CLUB: '/admin/stats/clubs',
  ADMIN_INQUIRY: '/admin/inquiry',
  SETTING: '/setting',
  INQUIRY: '/inquiry',
  GROUP: '/groups',
  GROUP_DETAIL: '/groups/detail',
};

export default ROUTE;
